// Approved public product guidance only. Keep answers aligned with the listed
// implementation sources; never retrieve private records or arbitrary documents.
export const helpRoutes = {
  attendance: { href: "/attendance", label: "Attendance" },
  reports: { href: "/reports", label: "Daily activity reports" },
  history: { href: "/history", label: "Attendance history" },
  calendar: { href: "/calendar", label: "Report calendar" },
  settings: { href: "/settings", label: "Profile and internship" },
  home: { href: "/", label: "Home" },
  allReports: { href: "/reports/all", label: "All saved reports" },
} as const;

export type HelpTopic = keyof typeof helpRoutes;
export type HelpArticle = { id: string; title: string; answer: string; topic: HelpTopic; source: string; matches: RegExp[] };
export const starterQuestions = [
  "How do I record time out?", "How do I submit my DAR?",
  "How does Draft with AI work?", "Why are my hours not credited?",
] as const;

export const articles: readonly HelpArticle[] = [
  { id: "help-capabilities", title: "What you can ask Help", topic: "home", source: "Daybook Help capabilities",
    matches: [/\bwhat (?:questions|can i ask|can you (?:do|help|answer))\b/, /\b(?:how (?:can|do) (?:you help|i use (?:you|this chat|help))|what are you|help topics|your capabilities)\b/],
    answer: "You can ask how to use attendance, credited hours, DARs, Draft with AI, PDF/DOCX downloads, imports, calendar, reminders, profile settings, and internship progress. For example: 'How do I record time out?', 'How does Draft with AI work?', or 'How do I download a past report?' You can also ask which model powers Help or whose account you are signed into. This chat explains features; it cannot send reports or change records. To turn your notes into activity rows, use Draft with AI in the report editor." },
  { id: "dar-definition", title: "What DAR means", topic: "reports", source: "Daily Activity Report template and report editor",
    matches: [/\b(?:meaning|definition) of (?:a |the )?dar\b/, /\bdar (?:meaning|definition)\b/, /\bwhat(?: is|'s) (?:a |the )?dar\s*[?.!]*$/, /\b(?:what does (?:a |the )?dar|dar) (?:mean|stand for|stands for)\b/],
    answer: "DAR stands for Daily Activity Report. In Daybook, it records your project, task description, Completed/Ongoing status, and remarks or blockers for a workday. Open Reports to create or review one." },
  { id: "time-out", title: "Record time out", topic: "attendance", source: "Attendance form and workflow",
    matches: [/\b(?:time[ -]?out|clock out)\b/],
    answer: "Open Attendance and select the workday. Enter your time out and save the entry. Today’s Add time out button opens that day directly. A time-in-only entry earns no hours until time out is saved. Time out must be after time in on the same day." },
  { id: "time-in", title: "Record time in", topic: "attendance", source: "Attendance form and workflow",
    matches: [/\b(?:time[ -]?in|clock in)\b/],
    answer: "Open Attendance, select a weekday, choose Office or WFH, and enter time in. You can save an open entry and complete time out later. Future dates, weekends, duplicate workdays, and overnight entries are not supported." },
  { id: "absence", title: "Mark an absence", topic: "attendance", source: "Attendance absence workflow",
    matches: [/\b(?:absent|absence)\b/],
    answer: "Open Attendance for the weekday and select Absent, then save. An absence has no time in or time out and credits zero hours. The calendar shows the saved absence. You can edit the entry to change it back to attendance." },
  { id: "hours", title: "Credited hours", topic: "attendance", source: "Attendance calculation rules",
    matches: [/\bhours?\b.*\b(?:credit|credited|missing|zero|calculate|calculated|count|counted)\b/, /\b(?:calculate|calculated|credit|credited)\b.*\bhours?\b/, /\blunch\b/],
    answer: "Only completed, non-absent attendance earns hours. Regular credit counts overlap with 08:30–12:00 and 13:00–18:30, excluding lunch. Open entries and absences earn zero. Work outside those windows does not earn regular credit. Optional overtime counts actual work after 18:30 when enabled for the entry." },
  { id: "overtime", title: "Optional overtime", topic: "attendance", source: "Attendance calculation rules",
    matches: [/\bovertime\b/],
    answer: "Enable overtime on the attendance entry if it should be included. Daybook counts actual work after 18:30, starting at the later of time in and 18:30. It does not calculate overtime simply because a day exceeds nine hours. This explains Daybook’s calculation, not employment or school policy." },
  { id: "submit", title: "Mark a DAR Submitted", topic: "reports", source: "Report editor: Next step",
    matches: [/\b(?:submit|submitted|submission|send|pass)\b.*\b(?:dar|report)\b/, /\b(?:dar|report)\b.*\b(?:submit|submitted|submission|send|pass)\b/],
    answer: "Open Reports for the date, save your activity rows, then choose Mark Ready. Ready requires completed attendance, a complete profile, and at least one complete activity row. Send the report to your project manager yourself. Then confirm ‘I have sent this report to my project manager’ and choose Mark Submitted. Daybook records your confirmation; it does not send the report for you. Downloads are optional before marking Submitted." },
  { id: "draft", title: "Create or continue a DAR", topic: "reports", source: "Report editor: activity rows and Save draft",
    matches: [/\b(?:create|start|save|write|edit|continue)\b.*\b(?:dar|report|draft)\b/, /\b(?:dar|report)\b.*\bdraft\b/],
    answer: "Open Reports and choose the weekday. Add your project, task description, Completed/Ongoing status, and remarks, then Save draft. You can also use Draft with AI in the editor to turn rough notes into rows you review first. You can draft while attendance is in progress. Save changes before marking Ready." },
  { id: "ai-draft", title: "Draft activities with AI", topic: "reports", source: "Report editor: Draft with AI",
    matches: [/\bdraft(?:ing)? with ai\b/, /\b(?:ai|gemini)\b.*\b(?:draft|drafting|write|writing|writes|fill|generate|activities|activity|dar|report)\b/, /\b(?:draft|drafting|write|writing|fill|generate|dar|report|notes?|activit\w*)\b.*\b(?:ai|gemini)\b/, /\b(?:turn|convert)\b.*\bnotes?\b/],
    answer: "Open Reports and choose an editable draft. In Draft with AI, type rough notes about your day and choose Draft activities. Google Gemini turns them into project, task, status, and remarks rows marked AI draft. Nothing is saved until you review, edit, and choose Save draft. Tasks stay Ongoing unless your notes say they're done. Only your notes and the report date are sent; notes with emails, phone numbers, or passwords are blocked. Limits: 5 drafts per minute and 30 per day. If the panel is missing, AI drafting isn't enabled on this Daybook." },
  { id: "review", title: "Needs review and revisions", topic: "reports", source: "Report editor: attendance correction notice",
    matches: [/\bneeds review\b/, /\b(?:reopen|revision|updated version|mark ready)\b/],
    answer: "Attendance changes can make a Ready or Submitted report’s saved hours outdated. Open the latest report and choose Create updated version, review the activities and corrected hours, save, and mark Ready again when prerequisites are complete. Earlier snapshots remain saved. A report needing review cannot be marked Submitted until resolved." },
  { id: "export", title: "Download a report", topic: "reports", source: "Report editor: download controls",
    matches: [/\b(?:download|export)\b.*\b(?:dar|report|pdf|docx)\b/, /\b(?:pdf|docx)\b.*\b(?:download|export)\b/],
    answer: "Save your report changes first. Saved Drafts offer DOCX/PDF previews, even while attendance is open; previews count completed attendance only. Ready and Submitted reports offer downloads in Next step, available afterward too. DOCX downloads use archived files. PDF downloads use the current template and the report's saved details, including past reports. Filenames follow DAR_LASTNAME_MMDDYY.docx or .pdf." },
  { id: "import", title: "Import and review a report", topic: "reports", source: "Report import review interface",
    matches: [/\bimport\b.*\b(?:dar|report|pdf|docx)\b/],
    answer: "Use the import controls in an editable report draft and select a DOCX or text-based PDF up to 4 MB. DOCX can import activity rows; PDF imports headers only. Review differences before applying anything. Imports never auto-save and do not replace attendance-derived hours. Choose Save draft to keep applied rows." },
  { id: "caught-up", title: "Attendance caught-up message", topic: "home", source: "Dashboard: earlier unfinished attendance",
    matches: [/\b(?:caught[ -]?up|needs attention)\b/],
    answer: "Caught up on attendance means no earlier attendance entries are missing time out. It does not mean every DAR is Submitted or all reminders are cleared. Today’s time-out reminder, unfinished DARs, and reports needing review can still appear in Reminders." },
  { id: "reminders", title: "Reminders and preferences", topic: "home", source: "Reminders popup and reminder rules",
    matches: [/\b(?:reminder|reminders|notification|notifications|alerts)\b/],
    answer: "Open the header bell to see active reminders and preferences. Today’s open-attendance time-out and DAR reminders start at 18:20 Philippine time, ten minutes before the standard 18:30 time out. Completed attendance can prompt a DAR earlier. Dismissals and type preferences apply to your account in this browser only. Dismissing a reminder does not change records. These are in-app reminders, not push or email delivery." },
  { id: "calendar", title: "Use the calendar", topic: "calendar", source: "Report calendar and day details",
    matches: [/\bcalendar\b/],
    answer: "Open Calendar to browse months, see credited hours, absences, report statuses, and monthly totals. Select a past or current weekday for attendance and report details and editing links. A missing-report indicator means completed, non-absent attendance has no saved report; a saved Draft is not the same as a Submitted report." },
  { id: "account-menu", title: "Account menu, appearance, and sign out", topic: "settings", source: "Header account menu",
    matches: [/\b(?:sign ?out|log ?out|logout|account menu|dark mode|light mode|theme|appearance)\b/],
    answer: "Your initials in the top right open the account menu on every screen. It shows your name and email, and has Profile & internship, Appearance (light or dark), and Sign out. Press Escape or tap outside to close it." },
  { id: "target", title: "Target and completion estimate", topic: "settings", source: "Profile form and dashboard forecast",
    matches: [/\b(?:target|required hours|completion estimate|estimated completion|remaining hours|progress)\b/],
    answer: "Open the account menu (your initials, top right) → Profile & internship to set your required internship hours and report details. Home compares completed attendance with your target. The estimated completion uses your latest ten completed, non-absent workdays and future Monday–Friday dates after today. It does not account for future holidays or leave and is not a guaranteed finish date." },
  { id: "history", title: "Find and correct attendance", topic: "history", source: "Attendance history and filters",
    matches: [/\battendance history\b/, /\b(?:correct|edit|delete|find)\b.*\battendance\b/],
    answer: "Open More → Attendance history to filter by date, location, or status and open saved entries. Edit the relevant date to correct attendance. Deleting requires confirmation. Attendance corrections can flag existing Ready or Submitted reports for review." },
  { id: "all-reports", title: "Find saved reports", topic: "allReports", source: "All reports listing and filters",
    matches: [/\b(?:all saved reports|all reports|report history|saved reports)\b/],
    answer: "Open More → All reports to browse saved versions across dates. Filter by date range and status; select a row to open that exact report version. Reports opens the editor for a selected date, while All reports shows saved versions." },
  { id: "profile", title: "Profile and sign-in", topic: "settings", source: "Profile form and Google registration rollout",
    matches: [/\b(?:profile|school|department|last name|sign in|log in|login|sign up|signup|register|google)\b/],
    answer: "Google registration is the current rollout. After signing in, open the account menu (your initials, top right) → Profile & internship to set your full name, last name, school, department/team, and required internship hours. Complete these details before marking a DAR Ready. Existing password sign-in remains available; email registration is disabled by default until configured." },
];
